# renew_before_expiry = 30 days
version = 2.9.0
archive_dir = /home/bq/docker-foswiki/certconfig/archive/wiki.machs.org
cert = /home/bq/docker-foswiki/certconfig/live/wiki.machs.org/cert.pem
privkey = /home/bq/docker-foswiki/certconfig/live/wiki.machs.org/privkey.pem
chain = /home/bq/docker-foswiki/certconfig/live/wiki.machs.org/chain.pem
fullchain = /home/bq/docker-foswiki/certconfig/live/wiki.machs.org/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = 7f48e205487ed7248388f48ad9daa6e6
config_dir = /home/bq/docker-foswiki/certconfig
work_dir = /home/bq/docker-foswiki/certwork
logs_dir = /home/bq/docker-foswiki/certlogs
authenticator = manual
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
